sudo: required
dist: xenial
language: nix
script:
  - nix-shell --run make
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: purs
