# This file was generated by Psc-Package2Nix
# You will not want to edit this file.
# To change the contents of this file, first fork Psc-Package2Nix
# And edit the $file_template

{ pkgs ? import <nixpkgs> {} }:

let
  inputs = {

    "aff" = pkgs.stdenv.mkDerivation {
      name = "aff";
      version = "v5.0.2";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-aff.git";
        rev = "v5.0.2";
        sha256 = "0jhqaimcg9cglnby0rn5xnrllcjj9mlb5yp6zqpy8b9zpg744v7d";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "affjax" = pkgs.stdenv.mkDerivation {
      name = "affjax";
      version = "v7.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-affjax.git";
        rev = "v7.0.0";
        sha256 = "1p5137apy8m4xfz79bza0ig5qcs8bn0fr1jsj03l850cs0kx5lip";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "argonaut-core" = pkgs.stdenv.mkDerivation {
      name = "argonaut-core";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-argonaut-core.git";
        rev = "v4.0.1";
        sha256 = "0rvqgm07ikbw7832fb9kb1gxwzd8cnjl9r58rdciz0jy3vkb22dm";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "arraybuffer-types" = pkgs.stdenv.mkDerivation {
      name = "arraybuffer-types";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-arraybuffer-types.git";
        rev = "v2.0.0";
        sha256 = "059a8n49yhl46l1b1j2qj4ichzq6dzj29ajkfvw88npzj5w2rshy";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "arrays" = pkgs.stdenv.mkDerivation {
      name = "arrays";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-arrays.git";
        rev = "v5.0.0";
        sha256 = "08zr13k6r1vfn4yicnqa2z1bna93imdi6yhara93wq0k5pivmk10";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "avar" = pkgs.stdenv.mkDerivation {
      name = "avar";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-avar.git";
        rev = "v3.0.0";
        sha256 = "14g05jm2xricy5b9vn4k4lhc9lzi5jvpvv85h10s17kn4wwi9igk";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "bifunctors" = pkgs.stdenv.mkDerivation {
      name = "bifunctors";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-bifunctors.git";
        rev = "v4.0.0";
        sha256 = "1bdra5fbkraglqrrm484vw8h0wwk48kzkn586v4y7fg106q1q386";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "catenable-lists" = pkgs.stdenv.mkDerivation {
      name = "catenable-lists";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-catenable-lists.git";
        rev = "v5.0.0";
        sha256 = "1zhc6mfgzkahrnbrl39vdj6biy75gibmayw8ahj9a23amsggs6df";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "colors" = pkgs.stdenv.mkDerivation {
      name = "colors";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/sharkdp/purescript-colors.git";
        rev = "v5.0.0";
        sha256 = "05bkfqllfpkh7nj0nzgd5p387hlpk0x35nam1i6xm3vzma9csj18";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "console" = pkgs.stdenv.mkDerivation {
      name = "console";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-console.git";
        rev = "v4.1.0";
        sha256 = "1rc9b53q0l7g37113nspdcxcysg19wfq0l9d84gys8dp3q9n8vbf";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "const" = pkgs.stdenv.mkDerivation {
      name = "const";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-const.git";
        rev = "v4.0.0";
        sha256 = "1fzj2zak5a59lxg7vhxsp24hqydhxs8iq89rbl7qm4zcqb0lvw70";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "contravariant" = pkgs.stdenv.mkDerivation {
      name = "contravariant";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-contravariant.git";
        rev = "v4.0.0";
        sha256 = "0vvcgfclx236kg4y76nwih787wyqacq8mmx42q64xzl964yrwxkk";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "control" = pkgs.stdenv.mkDerivation {
      name = "control";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-control.git";
        rev = "v4.1.0";
        sha256 = "10703zvsnjm5fc74k6wzjsvpsfyc3jci3jxhm7rxf7ymya9z1z53";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "coroutines" = pkgs.stdenv.mkDerivation {
      name = "coroutines";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-coroutines.git";
        rev = "v5.0.0";
        sha256 = "1jax7by8kn9fjg00avhziy3n18i3510iwzs3d73ziplanbw4qw4k";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "css" = pkgs.stdenv.mkDerivation {
      name = "css";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-css.git";
        rev = "v4.0.0";
        sha256 = "0f6gib6rp20qz08vramw7k6kv2ck315lmshjpii8zmkjb5ya0w55";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "datetime" = pkgs.stdenv.mkDerivation {
      name = "datetime";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-datetime.git";
        rev = "v4.0.0";
        sha256 = "0zpjpnsnn95cscc95p9p59g7fvcc4qcl5yjmlrkjln4swi62jggd";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "distributive" = pkgs.stdenv.mkDerivation {
      name = "distributive";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-distributive.git";
        rev = "v4.0.0";
        sha256 = "0zbn0yq1vv7fbbf1lncg80irz0vg7wnw9b9wrzxhdzpbkw4jinsl";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "dom-indexed" = pkgs.stdenv.mkDerivation {
      name = "dom-indexed";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-dom-indexed.git";
        rev = "v6.0.0";
        sha256 = "0gbmli54smjwwpwq0pa44vjqsbhhyfvm4c56issrd8f405wgrwn0";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "effect" = pkgs.stdenv.mkDerivation {
      name = "effect";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-effect.git";
        rev = "v2.0.0";
        sha256 = "0l46xqz39khf2c779d8mvax1fp2phy5sf8qdn31x67dz389mjr81";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "either" = pkgs.stdenv.mkDerivation {
      name = "either";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-either.git";
        rev = "v4.0.0";
        sha256 = "0c72wk4hdcayj1jvwk1i6fny8r9iflxblvng6a265hb9r8gnjnwn";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "enums" = pkgs.stdenv.mkDerivation {
      name = "enums";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-enums.git";
        rev = "v4.0.0";
        sha256 = "1g2zns5xsdb9xyv14iwyvg2x39hjpsyvvrkh8gy1pqgzv6frmb18";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "exceptions" = pkgs.stdenv.mkDerivation {
      name = "exceptions";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exceptions.git";
        rev = "v4.0.0";
        sha256 = "17s0rg9k4phivhx9j3l2vqqfdhk61gpj1xfqy8w6zj3rnxj0b2cv";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "exists" = pkgs.stdenv.mkDerivation {
      name = "exists";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-exists.git";
        rev = "v4.0.0";
        sha256 = "0bbdbw3jaqyi8dj2d52zvfgx4vl84d8cr6hp43vy8lfjfcbj0wlk";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "foldable-traversable" = pkgs.stdenv.mkDerivation {
      name = "foldable-traversable";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foldable-traversable.git";
        rev = "v4.0.0";
        sha256 = "0dscsshm80j08qyv504mj77xb4f1bic9jbzqlgd2vbx6wpdcv9ll";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "foreign" = pkgs.stdenv.mkDerivation {
      name = "foreign";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign.git";
        rev = "v5.0.0";
        sha256 = "15mz2s4f8crkd721z4df2aag4s0wil6fs07cpcmi7dpnkn7a4nab";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "foreign-object" = pkgs.stdenv.mkDerivation {
      name = "foreign-object";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-foreign-object.git";
        rev = "v1.0.0";
        sha256 = "19jz8nqkj2h24r1ay08ba65qqpg4b0a1x31ncsq7jg77ayfhl4ms";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "fork" = pkgs.stdenv.mkDerivation {
      name = "fork";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-fork.git";
        rev = "v4.0.0";
        sha256 = "1jygqzyci40c28gw2ygnx8v52hilhajj1bdpn7ndvss4i7yh1lcp";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "form-urlencoded" = pkgs.stdenv.mkDerivation {
      name = "form-urlencoded";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-form-urlencoded.git";
        rev = "v4.0.1";
        sha256 = "14nb7mslmbms4wn4j6a7nrz8xmnach3qgcf8i1hgql1c8j7zkqz8";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "free" = pkgs.stdenv.mkDerivation {
      name = "free";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-free.git";
        rev = "v5.1.0";
        sha256 = "0f093s5wvbip547fyfxyjqn60z5ay11hs9vzw1h480307vpzq3wm";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "freeap" = pkgs.stdenv.mkDerivation {
      name = "freeap";
      version = "v5.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/ethul/purescript-freeap.git";
        rev = "v5.0.1";
        sha256 = "007840vpxa4gz0fvjbahyky2xzz625gzfaiy2wjpb50d9qacsr7y";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "freet" = pkgs.stdenv.mkDerivation {
      name = "freet";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-freet.git";
        rev = "v4.0.0";
        sha256 = "1kpgggwimxjvdvhn6s7z4lzg3yw1rqg5f7pyamx9gh232s4va40i";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "functions" = pkgs.stdenv.mkDerivation {
      name = "functions";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functions.git";
        rev = "v4.0.0";
        sha256 = "0675k5kxxwdvsjs6a3is8pwm3hmv0vbcza1b8ls10gymmfz3k3hj";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "functors" = pkgs.stdenv.mkDerivation {
      name = "functors";
      version = "v3.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-functors.git";
        rev = "v3.0.1";
        sha256 = "11phmaadh467k7q10sixg353m3l0lh9vzv8xrp8xw8zipk92f03n";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "gen" = pkgs.stdenv.mkDerivation {
      name = "gen";
      version = "v2.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-gen.git";
        rev = "v2.1.0";
        sha256 = "0ddsfb6a23rahkw9d3ymp2sf6d6vxndj73y61cdv74zrlr2nx74p";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "generics-rep" = pkgs.stdenv.mkDerivation {
      name = "generics-rep";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-generics-rep.git";
        rev = "v6.0.0";
        sha256 = "0p9c29hgd418hqfa0nmgrw84j3daabbx9bxys8pnlgq4dmglkzyv";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "globals" = pkgs.stdenv.mkDerivation {
      name = "globals";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-globals.git";
        rev = "v4.0.0";
        sha256 = "150mc0kv0cb5fkx0szicwczjr54bglmlyaynj2grf1r4gnjg967s";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "halogen" = pkgs.stdenv.mkDerivation {
      name = "halogen";
      version = "v5.0.0-pre";
      src = pkgs.fetchgit {
        url = "https://github.com/entyo/purescript-halogen.git";
        rev = "v5.0.0-pre";
        sha256 = "04mhcnbhpbd7nrhycd9g2vgigzcyqaygiqp58i84qsicspj1ny41";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "halogen-css" = pkgs.stdenv.mkDerivation {
      name = "halogen-css";
      version = "v8.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen-css.git";
        rev = "v8.0.0";
        sha256 = "1a8sj8ydfnvj3vh2l3f0yyd69y7v4qki1a5m99n0v2aqc1y6nrzl";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "halogen-vdom" = pkgs.stdenv.mkDerivation {
      name = "halogen-vdom";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/slamdata/purescript-halogen-vdom.git";
        rev = "v4.0.0";
        sha256 = "0fjhyyvmi4lg2ds5ahxk4il0fq19knj90crw6hz75f0vvid9rily";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "http-methods" = pkgs.stdenv.mkDerivation {
      name = "http-methods";
      version = "v4.0.2";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-http-methods.git";
        rev = "v4.0.2";
        sha256 = "1wfgrlnl33bcqw54hbc8icah2fi0rvi5zxhz07665vy9p5ppvkqs";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "identity" = pkgs.stdenv.mkDerivation {
      name = "identity";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-identity.git";
        rev = "v4.0.0";
        sha256 = "0jw61rk4308qmbjxkdb37fdw2r08pzh8z3lg2x29f9l9f7ra5ggw";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "integers" = pkgs.stdenv.mkDerivation {
      name = "integers";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-integers.git";
        rev = "v4.0.0";
        sha256 = "17d4bfpnrmbxlc7hhhrvnli70ydaqyr26zgvc9q52a76zgdcb4cf";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "invariant" = pkgs.stdenv.mkDerivation {
      name = "invariant";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-invariant.git";
        rev = "v4.1.0";
        sha256 = "1fimpbh3yb7clvqxcdf4yf9im64z0v2s9pbspfacgq5b4vshjas9";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "js-date" = pkgs.stdenv.mkDerivation {
      name = "js-date";
      version = "v6.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-js-date.git";
        rev = "v6.0.0";
        sha256 = "19qyzbr4a1ca8znbd8gcbz0a801f5p1v238ky3408gdx4ba32zjd";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "lazy" = pkgs.stdenv.mkDerivation {
      name = "lazy";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lazy.git";
        rev = "v4.0.0";
        sha256 = "156q89l4nvvn14imbhp6xvvm82q7kqh1pyndmldmnkhiqyr84vqv";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "lists" = pkgs.stdenv.mkDerivation {
      name = "lists";
      version = "v5.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-lists.git";
        rev = "v5.2.0";
        sha256 = "1cdg54p731vc6gzq9vbiygpg7l5lgprmz5mv9c22jyqah9rh2fdq";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "math" = pkgs.stdenv.mkDerivation {
      name = "math";
      version = "v2.1.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-math.git";
        rev = "v2.1.1";
        sha256 = "1msmy9w7y6fij62sdc55w68gpwkhm6lhgc8qjisjk4sxx1wdg1rr";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "maybe" = pkgs.stdenv.mkDerivation {
      name = "maybe";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-maybe.git";
        rev = "v4.0.0";
        sha256 = "06mm4a6lbp5by14vms3lyhqp64211lwnq1dqbaazvdp0afykx1z5";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "media-types" = pkgs.stdenv.mkDerivation {
      name = "media-types";
      version = "v4.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-media-types.git";
        rev = "v4.0.1";
        sha256 = "0ykwmxrhmwfy6c5mxjxa43xdf5xqakrqyvr5fn986yad50gjqj75";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "newtype" = pkgs.stdenv.mkDerivation {
      name = "newtype";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-newtype.git";
        rev = "v3.0.0";
        sha256 = "0qvk9p41miy806b05b4ikbr3if0fcyc35gfrwd2mflcxxp46011c";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "nonempty" = pkgs.stdenv.mkDerivation {
      name = "nonempty";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-nonempty.git";
        rev = "v5.0.0";
        sha256 = "1vz174sg32cqrp52nwb2vz9frrzmdwzzlgl4vc2cm5wlf2anirxj";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "now" = pkgs.stdenv.mkDerivation {
      name = "now";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-now.git";
        rev = "v4.0.0";
        sha256 = "18h5pif2dy4r7w1xg2zw4mvdqlar9xqp3rawkiavmsc946ncf3zs";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "nullable" = pkgs.stdenv.mkDerivation {
      name = "nullable";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-nullable.git";
        rev = "v4.0.0";
        sha256 = "1ppv7qm9lnn26f8v1lpc5idx5kd7m0mdi48zazgz18hkfr5wxma5";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "ordered-collections" = pkgs.stdenv.mkDerivation {
      name = "ordered-collections";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-ordered-collections.git";
        rev = "v1.0.0";
        sha256 = "1yw5581clrw25rzhfgdk3qxb42h2g34g86a4252f4wygqndcxphc";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "orders" = pkgs.stdenv.mkDerivation {
      name = "orders";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-orders.git";
        rev = "v4.0.0";
        sha256 = "13p1sm4dxkmxhld9x5qqg62iiajjb3qpzs66c1r24y5fs4zsfry4";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "parallel" = pkgs.stdenv.mkDerivation {
      name = "parallel";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-parallel.git";
        rev = "v4.0.0";
        sha256 = "1d5bnagabw2k8yxywkygwrpblb2ggqh2fhpqfrx2sj1y53x332hg";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "partial" = pkgs.stdenv.mkDerivation {
      name = "partial";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-partial.git";
        rev = "v2.0.0";
        sha256 = "0nw5989ydin2d12b97ch4pdynxkq91xpj7yym5gpd5fpbgy36mdi";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "prelude" = pkgs.stdenv.mkDerivation {
      name = "prelude";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-prelude.git";
        rev = "v4.1.0";
        sha256 = "1pwqhsba4xyywfflma5rfqzqac1vmybwq7p3wkm4wsackvbn34h5";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "profunctor" = pkgs.stdenv.mkDerivation {
      name = "profunctor";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-profunctor.git";
        rev = "v4.0.0";
        sha256 = "1v4kvmhmiwznd4lswp9339h64pgv5zvd3vm1q7gzj70767a3941i";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "profunctor-lenses" = pkgs.stdenv.mkDerivation {
      name = "profunctor-lenses";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-profunctor-lenses.git";
        rev = "v4.0.0";
        sha256 = "09wbwqq5sbrq414i0ks1i8lvw4snsslaby2axfyvrwxnliybk9qz";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "proxy" = pkgs.stdenv.mkDerivation {
      name = "proxy";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-proxy.git";
        rev = "v3.0.0";
        sha256 = "0rqf25b1n9p5sgx7gdsxwrfv9rb3sqxgqmqpp5kdm30lfk7snz24";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "record" = pkgs.stdenv.mkDerivation {
      name = "record";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-record.git";
        rev = "v1.0.0";
        sha256 = "1vx6qlcg8x8cij3jsf52gqnd1dvam36pw83x4sad1ddir2s5h0i8";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "refs" = pkgs.stdenv.mkDerivation {
      name = "refs";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-refs.git";
        rev = "v4.1.0";
        sha256 = "08161iy1xbafzblv033v84156azpcqkiw9v9d6gliphrq5fm17gm";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "simple-json" = pkgs.stdenv.mkDerivation {
      name = "simple-json";
      version = "v4.2.0";
      src = pkgs.fetchgit {
        url = "https://github.com/justinwoo/purescript-simple-json.git";
        rev = "v4.2.0";
        sha256 = "1iyiy2hl9dsc9y34n6izn4qpj72wpv9a45lj6k6br3vlmm2f00z1";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "st" = pkgs.stdenv.mkDerivation {
      name = "st";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-st.git";
        rev = "v4.0.0";
        sha256 = "0m2jkb9dmpbr8s1c20l7sm2q11y5rx8gqfiyspnyhq5apzkknjr0";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "strings" = pkgs.stdenv.mkDerivation {
      name = "strings";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-strings.git";
        rev = "v4.0.0";
        sha256 = "0i7i3irhx1l9abprll95fi374gp49qka0vbhk80cbnhmx1v5px5k";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "tailrec" = pkgs.stdenv.mkDerivation {
      name = "tailrec";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tailrec.git";
        rev = "v4.0.0";
        sha256 = "0z7k80nl8dgv8mc2w8xsl2n0637bd1l8ppxak8kaifgjjwa81hx3";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "these" = pkgs.stdenv.mkDerivation {
      name = "these";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-these.git";
        rev = "v4.0.0";
        sha256 = "0ywwpbcz1d0pdi3f9h9kla52vq1if8zwdz7jq7lqz5s8zj8kyg5r";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "transformers" = pkgs.stdenv.mkDerivation {
      name = "transformers";
      version = "v4.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-transformers.git";
        rev = "v4.1.0";
        sha256 = "1aazy1zk66lng8w0gjx2l7sqfr968gmibdxi4kd93zb7bw5vldvn";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "tuples" = pkgs.stdenv.mkDerivation {
      name = "tuples";
      version = "v5.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-tuples.git";
        rev = "v5.0.0";
        sha256 = "0vlhv4l2a2vb6rh5zfsjhbv7hy4vz9fa5p1ns0rk54xd2pzzlvgd";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "type-equality" = pkgs.stdenv.mkDerivation {
      name = "type-equality";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-type-equality.git";
        rev = "v3.0.0";
        sha256 = "1b7szyca5s96gaawvgwrw7fa8r7gqsdff7xhz3vvngnylv2scl3w";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "typelevel-prelude" = pkgs.stdenv.mkDerivation {
      name = "typelevel-prelude";
      version = "v3.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-typelevel-prelude.git";
        rev = "v3.0.0";
        sha256 = "0dn95n9jnk2ilw38cf9p8p6q3xad6ck1rq3r4jba92kmk4ql665r";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "unfoldable" = pkgs.stdenv.mkDerivation {
      name = "unfoldable";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unfoldable.git";
        rev = "v4.0.0";
        sha256 = "077vl30j3pxr3zw6cw7wd0vi22j92j8va15r26rn53wzbzcgr41j";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "unsafe-coerce" = pkgs.stdenv.mkDerivation {
      name = "unsafe-coerce";
      version = "v4.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript/purescript-unsafe-coerce.git";
        rev = "v4.0.0";
        sha256 = "0k9255mk2mz6xjb11pwkgfcblmmyvr86ig5kr92jwy95xim09zip";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "unsafe-reference" = pkgs.stdenv.mkDerivation {
      name = "unsafe-reference";
      version = "v3.0.1";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-contrib/purescript-unsafe-reference";
        rev = "v3.0.1";
        sha256 = "0q758dz59qz0li4s3w1qcg921xp5i5rh6i1l611iv7rr8cbj11al";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "variant" = pkgs.stdenv.mkDerivation {
      name = "variant";
      version = "v5.1.0";
      src = pkgs.fetchgit {
        url = "https://github.com/natefaubion/purescript-variant.git";
        rev = "v5.1.0";
        sha256 = "045qkiv9j0pbdffyzn4r3gr75ahl7h9kxmib6q1bpds1c490pcg6";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-clipboard" = pkgs.stdenv.mkDerivation {
      name = "web-clipboard";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-clipboard.git";
        rev = "v1.0.0";
        sha256 = "0zbhrm4ck8a8wf1knpmxccfyws07frld8i70wnkwjfan1pgdji63";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-dom" = pkgs.stdenv.mkDerivation {
      name = "web-dom";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-dom.git";
        rev = "v1.0.0";
        sha256 = "070ybc5xzpsh75p618ll9j0lzxqgvc4cl5cdrn71v0vagmyhgm8h";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-events" = pkgs.stdenv.mkDerivation {
      name = "web-events";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-events.git";
        rev = "v1.0.0";
        sha256 = "1j6gkap9ap1ik7aiiyxwdmvjfhfrw73dq5hi9a671k5prlma7v3k";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-file" = pkgs.stdenv.mkDerivation {
      name = "web-file";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-file.git";
        rev = "v1.0.0";
        sha256 = "14kzwrwbfacxr4krfriy8qx13wnhiydrgs6hp59a7bmx58w0ifks";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-html" = pkgs.stdenv.mkDerivation {
      name = "web-html";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-html.git";
        rev = "v1.0.0";
        sha256 = "1xcv91h1d6qvgnidgvcwgyi5dvainrc9sqrll6xl7gwkmaj7nk61";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-storage" = pkgs.stdenv.mkDerivation {
      name = "web-storage";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-storage.git";
        rev = "v2.0.0";
        sha256 = "1lr4lswsp62kl21rl6jb377a0sya105sfimkxm3y22grx88l6vj1";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-touchevents" = pkgs.stdenv.mkDerivation {
      name = "web-touchevents";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-touchevents.git";
        rev = "v1.0.0";
        sha256 = "1avg7jljd1j7d0b7k7fbqxi90aa01awp9x17v53mynzg6gyvc8zb";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-uievents" = pkgs.stdenv.mkDerivation {
      name = "web-uievents";
      version = "v1.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-uievents.git";
        rev = "v1.0.0";
        sha256 = "1683ysabddnhsjiy70axpslagi2cp2ab3qd0r1qjx6ab2zjd6kc0";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };

    "web-xhr" = pkgs.stdenv.mkDerivation {
      name = "web-xhr";
      version = "v2.0.0";
      src = pkgs.fetchgit {
        url = "https://github.com/purescript-web/purescript-web-xhr.git";
        rev = "v2.0.0";
        sha256 = "05s3wp525wyvfz3rv456shvng9c0a4ncjdc7yxn2zglhq973km23";
      };
      dontInstall = true;
      buildPhase = ''
        cp -r $src $out
        rm -rf $out/.git
      '';
    };
};

in {
  inherit inputs;

  set = "halogen-master";
  source = "https://github.com/entyo/package-sets.git";
}
