version: 2.0

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/WatchingU

  workspace_root: &workspace_root
      /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install yarn
          command: sudo npm install -g yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command:
            ./node_modules/@angular/cli/bin/ng build --prod --base-href "https://entyo.github.io/WatchingU/"
            && mkdir -p /tmp/workspace
            && cp -r dist /tmp/workspace
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist
  deploy:
    <<: *container_config
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: Install angular-cli-ghpages
          command: sudo npm install -g angular-cli-ghpages
      - run:
          name: Deploy to ghpages
          command: cd /tmp/workspace && sudo ngh --name=$GH_EMAIL --email=$GH_NAME --repo=https://$GH_TOKEN@github.com/entyo/WatchingU.git --no-silent
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
